services:
  postgres:
    image: postgres:17.9
    container_name: flightdrift_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: flightdrift
    ports:
      - "5432:5432"
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgresql.conf:/etc/postgresql/postgresql.conf