CREATE USER weaver WITH PASSWORD 'weaver';

ALTER DATABASE weaver OWNER TO weaver;

GRANT ALL ON SCHEMA public TO weaver;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO weaver;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO weaver;